-- Migration para adicionar a coluna de ranking na tabela de cadastro
-- Mantém a migração segura em bancos novos ou existentes

CREATE TABLE IF NOT EXISTS tb_cadastro_ninja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    img_url VARCHAR(255),
    idade INTEGER,
    missoes_id BIGINT
);

ALTER TABLE tb_cadastro_ninja
ADD COLUMN IF NOT EXISTS rank VARCHAR(255);